var challengeRatingData = {
  '0': {proficiency: '+2', xp: '0'},
  '1/8': {proficiency: '+2', xp: '25'},
  '1/4': {proficiency: '+2', xp: '50'},
  '1/2': {proficiency: '+2', xp: '100'},
  '1': {proficiency: '+2', xp: '200'},
  '2': {proficiency: '+2', xp: '450'},
  '3': {proficiency: '+2', xp: '700'},
  '4': {proficiency: '+2', xp: '1,100'},
  '5': {proficiency: '+3', xp: '1,800'},
  '6': {proficiency: '+3', xp: '2,300'},
  '7': {proficiency: '+3', xp: '2,900'},
  '8': {proficiency: '+3', xp: '3,900'},
  '9': {proficiency: '+4', xp: '5,000'},
  '10': {proficiency: '+4', xp: '5,900'},
  '11': {proficiency: '+4', xp: '7,200'},
  '12': {proficiency: '+4', xp: '8,400'},
  '13': {proficiency: '+5', xp: '10,000'},
  '14': {proficiency: '+5', xp: '11,500'},
  '15': {proficiency: '+5', xp: '13,000'},
  '16': {proficiency: '+5', xp: '15,000'},
  '17': {proficiency: '+6', xp: '18,000'},
  '18': {proficiency: '+6', xp: '20,000'},
  '19': {proficiency: '+6', xp: '22,000'},
  '20': {proficiency: '+6', xp: '25,000'},
  '21': {proficiency: '+7', xp: '33,000'},
  '22': {proficiency: '+7', xp: '41,000'},
  '23': {proficiency: '+7', xp: '50,000'},
  '24': {proficiency: '+7', xp: '62,000'},
  '25': {proficiency: '+8', xp: '75,000'},
  '26': {proficiency: '+8', xp: '90,000'},
  '27': {proficiency: '+8', xp: '105,000'},
  '28': {proficiency: '+8', xp: '120,000'},
  '29': {proficiency: '+9', xp: '135,000'},
  '30': {proficiency: '+9', xp: '155,000'}
}
var challengeRatings = [
  '0',
  '1/8',
  '1/4',
  '1/2',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
  '25',
  '26',
  '27',
  '28',
  '29',
  '30'
]

var tumbeast = [{
  "slug": "tumbeast",
  "name": "Tumbeast",
  "size": "Knee-height",
  "type": "hellsite (affectionate) dweller",
  "subtype": "",
  "group": null,
  "alignment": "chaotic hungry",
  "armor_class": 10,
  "armor_desc": "oatmeal",
  "hit_points": 503,
  "hit_dice": "118d6+90",
  "speed": {
      "walk": 50,
      "climb": 50,
  },
  "strength": 12,
  "dexterity": 14,
  "constitution": 8,
  "intelligence": 1,
  "wisdom": 12,
  "charisma": 16,
  "strength_save": null,
  "dexterity_save": null,
  "constitution_save": null,
  "intelligence_save": null,
  "wisdom_save": null,
  "charisma_save": null,
  "perception": null,
  "skills": {
      "acrobatics": 4
  },
  "damage_vulnerabilities": "emotional",
  "damage_resistances": "",
  "damage_immunities": "psychic",
  "condition_immunities": "charmed, frightened",
  "senses": "passive Perception 12",
  "languages": "unsure, it doesn't seem to respond to anything",
  "challenge_rating": "0",
  "actions": [
      {
          "attack_bonus": 4,
          "damage_dice": "3d8+6",
          "desc": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) piercing damage.",
          "name": "Gnawing"
      },
      {
          "desc": "When Tumbeasts are not fed regularly, they band together and openly rebel in the server rooms which they call home, declaring anything they can get their tiny little paws on as viable food.",
          "name": "Mutiny"
      }
  ],
  "reactions": "",
  "legendary_desc": "",
  "legendary_actions": "",
  "special_abilities": [
      {
          "desc": "The elusive Tumbeast only shows up when there are no other results. Your filters found nothing.",
          "name": "Nothing Here"
      }
  ],
  "spell_list": [],
  "img_main": null,
  "document__slug": "",
  "document__title": "",
  "document__license_url": ""
}];

module.exports = {challengeRatingData, challengeRatings, tumbeast};